export enum QuarantineTriggerSource {
  DONOR_SCREENING = 'DONOR_SCREENING',
  TEMPERATURE_BREACH = 'TEMPERATURE_BREACH',
  MANUAL_OPERATOR_ACTION = 'MANUAL_OPERATOR_ACTION',
  ANOMALY_DETECTION = 'ANOMALY_DETECTION',
}

export enum QuarantineReasonCode {
  SCREENING_FAILURE = 'SCREENING_FAILURE',
  STORAGE_ANOMALY = 'STORAGE_ANOMALY',
  CONTAMINATION_SUSPECTED = 'CONTAMINATION_SUSPECTED',
  DONOR_LEVEL_EVENT = 'DONOR_LEVEL_EVENT',
  FAILED_DELIVERY = 'FAILED_DELIVERY',
  OTHER = 'OTHER',
}

export enum QuarantineReviewState {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED_RELEASE = 'APPROVED_RELEASE',
  APPROVED_DISCARD = 'APPROVED_DISCARD',
  CLOSED = 'CLOSED',
}

export enum QuarantineDisposition {
  RELEASE = 'RELEASE',
  DISCARD = 'DISCARD',
}
